#!/usr/bin/env bash
set -euo pipefail

ACCOUNT_FILE="${1:-Doc/accounts}"
ENV_FILE="${2:-.env.local}"

if [[ ! -f "$ACCOUNT_FILE" ]]; then
  echo "Missing account file: $ACCOUNT_FILE" >&2
  exit 1
fi

set -a
# shellcheck disable=SC1090
source "$ACCOUNT_FILE"
set +a

if [[ -z "${AI_API_KEY:-}" ]]; then
  echo "AI_API_KEY is missing in $ACCOUNT_FILE" >&2
  exit 1
fi

AI_BASE_URL="${AI_BASE_URL:-https://dashscope.aliyuncs.com/compatible-mode/v1}"
AI_BASE_URL="${AI_BASE_URL%/}"
DASHSCOPE_BASE_URL="$AI_BASE_URL"
DASHSCOPE_BASE_URL="${DASHSCOPE_BASE_URL%/compatible-mode/v1}"

umask 077
{
  echo "# Generated by scripts/bootstrap_env.sh. Do not commit this file."
  echo "DASHSCOPE_API_KEY=$AI_API_KEY"
  echo "DASHSCOPE_BASE_URL=$DASHSCOPE_BASE_URL"
  echo ""
  echo "# AIDrama defaults to DashScope. OpenAI-compatible values are kept for optional switching."
  echo "LLM_PROVIDER=dashscope"
  echo "OPENAI_API_KEY=$AI_API_KEY"
  echo "OPENAI_BASE_URL=$AI_BASE_URL"
  echo "OPENAI_MODEL=qwen-plus"
  echo ""
  echo "# Keep video providers on DashScope unless vendor-direct keys are added later."
  echo "KLING_PROVIDER_MODE=dashscope"
  echo "VIDU_PROVIDER_MODE=dashscope"
  echo "PIXVERSE_PROVIDER_MODE=dashscope"
  echo ""
  echo "NO_PROXY=*.aliyuncs.com,localhost,127.0.0.1"
  echo "no_proxy=*.aliyuncs.com,localhost,127.0.0.1"
} > "$ENV_FILE"

chmod 600 "$ENV_FILE"
echo "Wrote $ENV_FILE from $ACCOUNT_FILE. Secret values were not printed."
