#!/usr/bin/env bash
set -euo pipefail

ACCOUNT_FILE="${1:-Doc/accounts}"
ENV_FILE="${2:-.env.local}"
FALLBACK_ENV_FILE="${AIDRAMA_FALLBACK_ENV_FILE:-.env}"

set -a
if [[ -f "$ACCOUNT_FILE" ]]; then
  # shellcheck disable=SC1090
  source "$ACCOUNT_FILE"
elif [[ -f "$FALLBACK_ENV_FILE" ]]; then
  echo "Missing $ACCOUNT_FILE; using $FALLBACK_ENV_FILE for local development." >&2
  # shellcheck disable=SC1090
  source "$FALLBACK_ENV_FILE"
else
  echo "Missing account file: $ACCOUNT_FILE and fallback env: $FALLBACK_ENV_FILE" >&2
  exit 1
fi
set +a

AI_API_KEY="${AI_API_KEY:-${DASHSCOPE_API_KEY:-${OPENAI_API_KEY:-}}}"

if [[ -z "${AI_API_KEY:-}" ]]; then
  echo "AI_API_KEY or DASHSCOPE_API_KEY is missing in local config." >&2
  exit 1
fi

AI_BASE_URL="${AI_BASE_URL:-${DASHSCOPE_COMPATIBLE_BASE_URL:-${OPENAI_BASE_URL:-https://dashscope.aliyuncs.com/compatible-mode/v1}}}"
AI_BASE_URL="${AI_BASE_URL%/}"
DASHSCOPE_BASE_URL="${DASHSCOPE_BASE_URL:-$AI_BASE_URL}"
DASHSCOPE_BASE_URL="${DASHSCOPE_BASE_URL%/compatible-mode/v1}"
API_HOST="${API_HOST:-0.0.0.0}"
API_PORT="${API_PORT:-48217}"
FRONTEND_PORT="${FRONTEND_PORT:-39211}"

umask 077
{
  echo "# Generated by scripts/bootstrap_env.sh. Do not commit this file."
  echo "API_HOST=$API_HOST"
  echo "API_PORT=$API_PORT"
  echo "FRONTEND_PORT=$FRONTEND_PORT"
  echo ""
  echo "DASHSCOPE_API_KEY=$AI_API_KEY"
  echo "DASHSCOPE_BASE_URL=$DASHSCOPE_BASE_URL"
  echo ""
  echo "# AIDrama defaults to DashScope. OpenAI-compatible values are kept for optional switching."
  echo "LLM_PROVIDER=dashscope"
  echo "OPENAI_API_KEY=$AI_API_KEY"
  echo "OPENAI_BASE_URL=$AI_BASE_URL"
  echo "OPENAI_MODEL=qwen-plus"
  echo ""
  echo "# Keep video providers on DashScope unless vendor-direct keys are added later."
  echo "KLING_PROVIDER_MODE=dashscope"
  echo "VIDU_PROVIDER_MODE=dashscope"
  echo "PIXVERSE_PROVIDER_MODE=dashscope"
  echo ""
  for optional_key in \
    ALIBABA_CLOUD_ACCESS_KEY_ID \
    ALIBABA_CLOUD_ACCESS_KEY_SECRET \
    OSS_BUCKET_NAME \
    OSS_ENDPOINT \
    OSS_BASE_PATH \
    KLING_ACCESS_KEY \
    KLING_SECRET_KEY \
    VIDU_API_KEY \
    ARK_API_KEY \
    PIXVERSE_API_KEY; do
    optional_value="${!optional_key:-}"
    if [[ -n "$optional_value" ]]; then
      echo "$optional_key=$optional_value"
    fi
  done
  echo ""
  echo "NO_PROXY=*.aliyuncs.com,localhost,127.0.0.1"
  echo "no_proxy=*.aliyuncs.com,localhost,127.0.0.1"
} > "$ENV_FILE"

chmod 600 "$ENV_FILE"
echo "Wrote $ENV_FILE from $ACCOUNT_FILE. Secret values were not printed."
